language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: "Testing"
      script: 
        - npm test
    - stage: "Build & Deploy to Github Pages"
      before_deploy: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: build
        on:
          branch: master